services:
  caddy:
    container_name: caddy-server
    image: caddy/caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  web:
    build: .
    container_name: gateway
    restart: unless-stopped
    image: novqigarrix/gateway
    env_file:
      - .env

volumes:
  caddy_data:
  caddy_config: